@api = https://api.unsplash.com
@client-id = 0NFTl6pzGs4TGWeKUFUM-PAUhvxItEz62qtMb-LKrQE

###

GET {{api}}/photos
Authorization: Client-ID {{client-id}}

###
GET {{api}}/search/photos
  ?query=cat
Authorization: Client-ID {{client-id}}

###
GET {{api}}/photos
  ?id=rW-I87aPY5Y
Authorization: Client-ID {{client-id}}

###
GET {{api}}/photos/random
  ?query=cat
Authorization: Client-ID {{client-id}}
